src/routes/web.php
<?php

Route::group(['middleware' => ['admin']], function () {

    Route::prefix('admin')->group(function () {

        Route::get('/login', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\Auth\AdminLoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\Auth\AdminLoginController@login')->name('admin.login.submit');
        Route::post('/logout', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\Auth\AdminLoginController@logout')->name('admin.logout');

//        Route::post('/password/email', '\App\Http\Controllers\Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
//        Route::get('/password/reset', '\App\Http\Controllers\Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
//        Route::post('/password/reset', '\App\Http\Controllers\Auth\AdminResetPasswordController@reset');
//        Route::get('/password/reset/{token}', '\App\Http\Controllers\Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

        Route::get('/', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\AdminController@dashboard')->name('admin.dashboard');

//        Route::group(['middleware' => ['role:Super Admin,Admin']], function() {
            Route::resource('roles','LiteCode\AdminGentelella\App\Http\Controllers\Backend\RoleController',['as'=>'admin']);
//        });
//        Route::resource('permissions','LiteCode\AdminGentelella\App\Http\Controllers\Backend\PermissionController',['as'=>'admin']);
        Route::resource('admins','LiteCode\AdminGentelella\App\Http\Controllers\Backend\AdminUserController',['as'=>'admin']);
//
    });

});

src/app/Http/Controllers/Backend/RoleController.php
<?php

namespace LiteCode\AdminGentelella\App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth:admin', ['except' => ['logout']]);
//        $this->middleware('role:Super Admin');
        $this->middleware('permission:role-read');
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-update', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            if($request->guard_name){
                $permissions = Permission::where('guard_name', $request->guard_name)->orderBy('name','ASC')->get();
                return view('admin::pages.roles.components.permissions',compact('permissions'));
            }
            if($request->page){
                $roles = Role::orderBy('id','DESC')->paginate(10);
                return view('admin::pages.roles.components.paginateRoles',compact('roles'))
                    ->with('i', ($request->input('page', 1) - 1) * 5);
            }

        }
        $roles = Role::orderBy('id','DESC')->paginate(10);
        return view('admin::pages.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get();
        return view('admin::pages.roles.create',compact('permissions'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {//dd($request->all());
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'guard_name' => 'required',
            //'permission' => 'required',
        ]);


        $role = Role::create(['name' => $request->input('name'), 'guard_name' => $request->input('guard_name')]);
        if($request->input('permission')){
            $role->syncPermissions($request->input('permission'));
        }


        return redirect()->route('admin.roles.index')
            ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();


        return view('admin::pages.roles.show',compact('role','rolePermissions'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::where('guard_name',$role->guard_name)->get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();


        return view('admin::pages.roles.edit',compact('role','permissions','rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {//dd($request->all());
        $this->validate($request, [
            'name' => 'required',
            'guard_name' => 'required',
            //'permission' => 'required',
        ]);


        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->guard_name = $request->input('guard_name');
        $role->save();

        if($request->input('permission')) {
            $role->syncPermissions($request->input('permission'));
        }


        return redirect()->route('admin.roles.index')
            ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('admin.roles.index')
            ->with('success','Role deleted successfully');
    }
}

src/resources/views/backend/pages/roles/create.blade.php
@extends('admin::layouts.gentelella')

@section('title', 'Admins')

@section('content')

    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Roles</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>


        <div class="x_panel">
            <div class="x_title">
                <h2>New Role <!--<small>Click to validate</small>--></h2>
                <div class="nav navbar-right">
                    <a href="{{ route('admin.roles.index') }}" class="btn btn-default btn-md" title="All Admins"><i class="fa fa-bars"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <!-- start form for validation -->
                <form id="demo-form" action="{{ route('admin.roles.store') }}" method="post" enctype="multipart/form-data" data-parsley-validate>
                    @csrf
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{@old('name')}}" id="name" class="form-control" placeholder="Name" required />
                    @if ($errors->has('name'))
                        <div class="error">{{ $errors->first('name') }}</div>
                    @endif
                    <br>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <strong>Guards:</strong>
                        <div class="form-group">
                            @foreach(config('auth.guards') as $guard_name => $value)
                                <div class="form-check">
                                    <input class="form-check-input" value="{{$guard_name}}" name="guard_name" id="guard_name" type="radio"
                                    onclick="listRolePermission('{{$guard_name}}')">
                                    <label class="form-check-label">{{$guard_name}}</label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-9">
                        <strong>Permission:</strong>
                        <div class="form-group">
                            @if ($errors->has('permission'))
                                <div class="alert alert-error" role="alert" style="z-index: 1001;">
                                    {{ $errors->first('permission') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                            <div  id="createRolePermissions">
                                @foreach($permissions as $permission)
                                    <div class="form-check col-md-3">
                                        <input class="form-check-input" value="{{$permission->id}}" name="permission[]" id="permissions" type="checkbox" >
                                        <label class="form-check-label">{{$permission->name}}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br>

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{{ route('admin.roles.index') }}" class="btn btn-default" title="All Roles">Cancel</a>

                </form>
                <!-- end form for validations -->

            </div>
        </div>
    </div>

    @push('after-scripts')
        @include('admin::pages.roles.scripts.manageGuards')
    @endpush

@endsection

src/resources/views/backend/pages/roles/edit.blade.php
@extends('admin::layouts.gentelella')

@section('title', 'Admins')

@section('content')

    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Roles</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>


        <div class="x_panel">
            <div class="x_title">
                <h2>Edit Role <!--<small>Click to validate</small>--></h2>
                <div class="nav navbar-right">
                    <a href="{{ route('admin.roles.index') }}" class="btn btn-default btn-md" title="All Admins"><i class="fa fa-bars"></i></a>
                    <a href="{{ route('admin.roles.create') }}" class="btn btn-success btn-md" title="Create New"><i class="fa fa-plus-circle"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <!-- start form for validation -->
                <form id="demo-form" action="{{ route('admin.roles.update', $role->id) }}" method="post" enctype="multipart/form-data" data-parsley-validate>
                    @csrf
                    @method('PUT')
                    <label for="name">Name</label>
                    <input type="text" name="name" value="{{@$role->name??@@old('name')}}" id="name" class="form-control" placeholder="Name" required />
                    @if ($errors->has('name'))
                        <div class="error">{{ $errors->first('name') }}</div>
                    @endif
                    <br>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <strong>Permission:</strong>
                            @if ($errors->has('permission'))
                                <div class="alert alert-error" role="alert" style="z-index: 1001;">
                                    {{ $errors->first('permission') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                            <div  id="createRolePermissions">
                                @foreach($permissions as $permission)
                                    <div class="form-check col-md-3">
                                        <input class="form-check-input" value="{{$permission->id}}" name="permission[]" id="permissions" type="checkbox"
                                            @if(in_array($permission->id, $rolePermissions)) checked @endif >
                                        <label class="form-check-label">{{$permission->name}}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <br>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{{ route('admin.roles.index') }}" class="btn btn-default" title="All Quizzes">Cancel</a>

                </form>
                <!-- end form for validations -->

            </div>
        </div>
    </div>

    @push('after-scripts')
        @include('admin::scripts.deleteConfirmation')
    @endpush

@endsection

src/resources/views/backend/pages/roles/index.blade.php
@extends('admin::layouts.gentelella')

@section('title', 'Roles')

@section('content')

    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Roles</h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List roles <!--<small>basic table subtitle</small>--></h2>
                        <ul class="nav navbar-right ">
                            <a href="{{ route('admin.roles.create') }}" class="btn btn-success btn-md" title="Create New"><i class="fa fa-plus-circle"></i></a>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content" id="paginateRoles">

                                @include('admin::pages.roles.components.paginateRoles')

                    </div>
                </div>
            </div>

        </div>
    </div>
    <div id="showRoleContainer"></div>

    @push('after-scripts')
        @include('admin::pages.roles.scripts.pagination')
        @include('admin::scripts.deleteConfirmation')
    @endpush

@endsection