src/routes/web.php
<?php

Route::group(['middleware' => ['admin']], function () {

    Route::prefix('admin')->group(function () {

        Route::get('/login', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\Auth\AdminLoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\Auth\AdminLoginController@login')->name('admin.login.submit');
        Route::post('/logout', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\Auth\AdminLoginController@logout')->name('admin.logout');

//        Route::post('/password/email', '\App\Http\Controllers\Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
//        Route::get('/password/reset', '\App\Http\Controllers\Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
//        Route::post('/password/reset', '\App\Http\Controllers\Auth\AdminResetPasswordController@reset');
//        Route::get('/password/reset/{token}', '\App\Http\Controllers\Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

        Route::get('/', 'LiteCode\AdminGentelella\App\Http\Controllers\Backend\AdminController@dashboard')->name('admin.dashboard');

//        Route::group(['middleware' => ['role:Super Admin,Admin']], function() {
            Route::resource('roles','LiteCode\AdminGentelella\App\Http\Controllers\Backend\RoleController',['as'=>'admin']);
//        });
//        Route::resource('permissions','LiteCode\AdminGentelella\App\Http\Controllers\Backend\PermissionController',['as'=>'admin']);
        Route::resource('admins','LiteCode\AdminGentelella\App\Http\Controllers\Backend\AdminUserController',['as'=>'admin']);
//
    });

});

src/app/Http/Controllers/Backend/RoleController.php
<?php

namespace LiteCode\AdminGentelella\App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth:admin', ['except' => ['logout']]);
//        $this->middleware('role:Super Admin');
        $this->middleware('permission:role-read');
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-update', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            if($request->guard_name){
                $permissions = Permission::where('guard_name', $request->guard_name)->orderBy('name','ASC')->get();
                return view('admin::pages.roles.components.permissions',compact('permissions'));
            }
            if($request->page){
                $roles = Role::orderBy('id','DESC')->paginate(10);
                return view('admin::pages.roles.components.paginateRoles',compact('roles'))
                    ->with('i', ($request->input('page', 1) - 1) * 5);
            }

        }
        $roles = Role::orderBy('id','DESC')->paginate(10);
        return view('admin::pages.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get();
        return view('admin::pages.roles.create',compact('permissions'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {//dd($request->all());
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'guard_name' => 'required',
            //'permission' => 'required',
        ]);


        $role = Role::create(['name' => $request->input('name'), 'guard_name' => $request->input('guard_name')]);
        if($request->input('permission')){
            $role->syncPermissions($request->input('permission'));
        }


        return redirect()->route('admin.roles.index')
            ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();


        return view('admin::pages.roles.show',compact('role','rolePermissions'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::where('guard_name',$role->guard_name)->get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();


        return view('admin::pages.roles.edit',compact('role','permissions','rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {//dd($request->all());
        $this->validate($request, [
            'name' => 'required',
            'guard_name' => 'required',
            //'permission' => 'required',
        ]);


        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->guard_name = $request->input('guard_name');
        $role->save();

        if($request->input('permission')) {
            $role->syncPermissions($request->input('permission'));
        }


        return redirect()->route('admin.roles.index')
            ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('admin.roles.index')
            ->with('success','Role deleted successfully');
    }
}

src/resources/views/backend/pages/roles/components/paginateRoles.blade.php
{{ $roles->links() }}
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Guard name</th>
        <th>Permissions</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
        @foreach($roles as $role)
            <tr>
                <th scope="row">{{$role->id}}</th>
                <td style="width:140px">{{$role->name}}</td>
                <td><label class="badge badge-success">{{$role->guard_name}}</label></td>
                <td>
                    @foreach($role->permissions as $permission)
                        <label class="badge badge-success">{{$permission->name}}</label>
                    @endforeach
                </td>
                <td style="width:140px">
                    {{--<a href="{{ route('admin.quizzes.show', ['quiz' => $quiz->id]) }}" class="btn btn-sm btn-primary"><i class="fa fa-eye"></i></a>--}}
                    <a onclick="showQuiz({{$role->id}});" class="btn btn-sm btn-primary"><i class="fa fa-eye"></i></a>
                    <a href="{{ route('admin.roles.edit', ['admin' => $role->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a>
                    <a onclick="deleteConfirmation('<?php echo url('admin/roles/'.$role->id); ?>')" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        @endforeach
    </tbody>

</table>
{{ $roles->links() }}

src/resources/views/backend/pages/roles/components/permissions.blade.php
    @if(count($permissions) < 1)
        No permissions found for this guard!
    @endif

    @foreach($permissions as $permission)
        <div class="form-check col-md-3">
            <input class="form-check-input" value="{{$permission->id}}" name="permission[]" id="permissions" type="checkbox" >
            <label class="form-check-label">{{$permission->name}}</label>
        </div>
    @endforeach